services:

################### MANDATORY ###################

  mariadb:
    build:
      context: srcs/mariadb/build
      dockerfile: Dockerfile
    container_name: mariadb
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306/tcp"
    volumes:
      -  /home/julthoma/data/mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build:
      context: srcs/wordpress/build
      dockerfile: Dockerfile
    container_name: wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_URL: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_ADMIN_PASS: ${WP_ADMIN_PASS}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_EMAIL: ${WP_EMAIL}
      WP_PASS: ${WP_PASS}
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "9000:9000/tcp"
    volumes:
      -  /home/julthoma/data/wordpress/html:/var/www/html
    networks:
      - inception

  nginx:
    build:
      context: srcs/nginx/build
      dockerfile: Dockerfile
    container_name: nginx
    restart: unless-stopped
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - wordpress
      - adminer
    ports:
      - "443:443/tcp"
    volumes:
      -  /home/julthoma/data/nginx/logs:/var/log/nginx
      -  /home/julthoma/data/wordpress/html:/var/www/html
      -  /home/julthoma/data/nginx/certs:/etc/nginx/certs
    networks:
      - inception

################### BONUS ###################

  ftp_server:
    build:
      context: srcs/ftp/build
      dockerfile: Dockerfile
    container_name: ftp_server
    environment:
      - PUBLIC_IP=0.0.0.0
      - FTP_PASS=${FTP_PASS}
      - FTP_USER=${FTP_USER}
    ports:
      - "20-21:20-21/tcp"
      - "40000-40009:40000-40009/tcp"
    volumes:
      -  /home/julthoma/data/wordpress/html:/home/user
    networks:
      - inception

  adminer:
    build:
      context: srcs/adminer/build
      dockerfile: Dockerfile
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - mariadb
      - wordpress
    ports:
      - "8081:8080/tcp"
    networks:
      - inception

  redis:
    build:
      context: srcs/redis/build
      dockerfile: Dockerfile
    container_name: redis
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "6379:6379/tcp"
    networks:
      - inception

  cadvisor:
    build:
      context: srcs/cadvisor/build
      dockerfile: Dockerfile
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/run:/var/run:ro
    ports:
      - "8082:8080/tcp"
    networks:
      - inception

networks:
  inception:
    driver: bridge
